services:
  - type: static
    name: my-cdn          # You can change the name
    env: static
    buildCommand: ""      # Nothing to build
    publishPath: "/"      # Use the repo root as the publish directory
